<script setup lang="ts">
import {onMounted,ref} from 'vue'
import {useRouter} from 'vue-router'
import {useSettingsStore} from '@/stores/settings'
import type {ProjectPreferences} from '@/types/project'
const router=useRouter(),settings=useSettingsStore(),value=ref<ProjectPreferences>({maxTurns:8,contextMessages:12,defaultSource:'unknown',defaultState:'active'}),error=ref(''),saved=ref(false),busy=ref(false)
onMounted(async()=>{try{value.value=await window.baoyi.project.preferences()}catch(e){error.value=(e as Error).message}})
async function save(){busy.value=true;saved.value=false;error.value='';try{value.value=await window.baoyi.project.preferences(JSON.parse(JSON.stringify(value.value)));saved.value=true}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
</script>
<template><div class="project-settings"><section><h2>项目助手</h2><p>围绕当前项目连续对话，查看目录、说明与 Git 状态，整理项目资料。</p><div class="model-status"><span>{{settings.settings.ai.enabled&&settings.settings.ai.model?settings.settings.ai.model:'尚未启用模型'}}</span><button class="btn" @click="router.replace({name:'settings',query:{tab:'ai'}})">配置模型</button></div><p class="hint">沿用抱一的 AI 配置。对话时，项目资料及助手读取的文本会发送给你配置的模型服务。</p><label>每次对话最多调用轮数<input v-model.number="value.maxTurns" type="number" min="2" max="20"/></label><label>保留在模型上下文中的消息数<input v-model.number="value.contextMessages" type="number" min="2" max="30"/></label><p class="hint">完整记录保存在本地，每次只发送最近的消息。达到上限后可以继续追问。</p></section><section><h2>新项目默认值</h2><label>来源<select v-model="value.defaultSource"><option value="unknown">来源未标记</option><option value="self">自己建立</option><option value="third-party">第三方项目</option><option value="mixed">混合来源</option></select></label><label>状态<select v-model="value.defaultState"><option value="active">使用中</option><option value="maintaining">维护中</option><option value="paused">已暂停</option><option value="archived">已归档</option></select></label></section><p v-if="error" role="alert">{{error}}</p><div class="settings-actions"><button class="btn btn--primary" :disabled="busy" @click="save">保存项目偏好</button><span v-if="saved" role="status">已保存</span></div></div></template>
<style scoped>.project-settings{max-width:850px}.project-settings section{background:var(--bg-card);border:1px solid var(--divider);border-radius:10px;padding:24px;margin-bottom:22px}.project-settings h2{font-size:18px;margin:0 0 12px}.project-settings p{color:var(--text-sub);line-height:1.8;font-size:13px}.project-settings label{display:flex;align-items:center;justify-content:space-between;gap:20px;max-width:580px;padding:12px 0;font-size:14px}.project-settings input,.project-settings select{width:180px;border:1px solid var(--divider);background:var(--bg-base);padding:9px;border-radius:6px}.model-status{display:flex;gap:20px;align-items:center;color:var(--accent)}.settings-actions{display:flex;align-items:center;gap:15px}.settings-actions span{font-size:13px;color:var(--accent)}</style>
