<script setup lang="ts">
import { onMounted,ref } from 'vue'
import ProjectDialog from './ProjectDialog.vue'
import type { ProjectItem,ProjectEntry } from '@/types/project'
const props=defineProps<{item:ProjectItem;entry?:ProjectEntry}>(),emit=defineEmits<{close:[];saved:[]}>()
const model=ref<ProjectEntry>(props.entry?JSON.parse(JSON.stringify(props.entry)):{id:crypto.randomUUID(),label:'',type:'path',path:'',role:'资料',args:[],cwd:'',resourceId:''}),args=ref((props.entry?.args||[]).join('\n')),busy=ref(false),error=ref(''),resources=ref<Array<{id:string;name:string;path:string;kind:string}>>([])
onMounted(async()=>{try{resources.value=await window.baoyi.project.resources()}catch{}})
async function pick(directory:boolean,cwd=false){try{const value=await window.baoyi.project.pickPath(directory);if(value){if(cwd)model.value.cwd=value;else{model.value.path=value;if(!model.value.label)model.value.label=value.split(/[\\/]/).at(-1)||value}}}catch(e){error.value=(e as Error).message}}
function link(){const r=resources.value.find(r=>r.id===model.value.resourceId);if(r){model.value.path=r.path;model.value.label=r.name;model.value.type='path';model.value.role='关联资源'}}
async function save(){busy.value=true;error.value='';try{
  const entry={...model.value,args:args.value.split('\n').filter(Boolean)},entries=props.entry?props.item.entries.map(e=>e.id===entry.id?entry:e):[...props.item.entries,entry]
  await window.baoyi.project.update(props.item.id,JSON.parse(JSON.stringify({entries})));emit('saved');emit('close')
}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
</script>
<template><ProjectDialog :title="entry?'编辑入口':'添加入口'" :busy="busy" @close="emit('close')"><form id="project-entry" class="pj-form" @submit.prevent="save"><label class="pj-field">入口名称<input v-model="model.label" required maxlength="160" placeholder="例如：打开主稿、打开代码、阅读笔记"/></label><div class="pj-form-pair"><label class="pj-field">打开方式<select v-model="model.type" aria-label="打开方式" :disabled="!!model.resourceId"><option value="path">文件 / 目录 / 程序</option><option value="obsidian">Obsidian 笔记</option><option value="url">网页</option><option value="command">外部工具与参数</option></select></label><label class="pj-field">用途<input v-model="model.role" maxlength="60" placeholder="主稿、参考、工具…"/></label></div><label v-if="resources.length" class="pj-field">关联已有资源<select aria-label="关联已有资源" v-model="model.resourceId" @change="link"><option value="">手动选择位置</option><option v-for="r in resources" :key="r.id" :value="r.id">{{r.name}} · {{({software:'软件',game:'游戏',video:'影视',image:'图片'} as Record<string,string>)[r.kind]||r.kind}}</option></select></label><label class="pj-field">{{model.type==='url'?'网址':'完整路径'}}<input v-model="model.path" :readonly="!!model.resourceId" required placeholder="选择文件，或粘贴完整路径"/></label><div v-if="model.type!=='url'" class="pj-inline"><button class="pj-button" type="button"  :disabled="!!model.resourceId" @click="pick(false)">选择文件 / 程序</button><button class="pj-button" type="button"  :disabled="!!model.resourceId" @click="pick(true)">选择目录</button></div><template v-if="model.type==='command'"><label class="pj-field">启动参数（每行一个）<textarea v-model="args" rows="3" placeholder="例如：项目目录的完整路径"/></label><label class="pj-field">工作目录<div class="pj-inline"><input v-model="model.cwd"/><button class="pj-button" type="button" @click="pick(true,true)">选择</button></div></label><p class="pj-muted">选择已安装的 EXE 工具，例如代码编辑器；参数按行独立传递。</p></template><p v-if="model.type==='obsidian'" class="pj-muted">选择库内的 Markdown 文件，打开时交给 Obsidian 定位。</p><p v-if="error" class="pj-error" role="alert">{{error}}</p></form><template #footer><button class="pj-button" :disabled="busy" @click="emit('close')">取消</button><button class="pj-button pj-primary" form="project-entry" type="submit" :disabled="busy">保存入口</button></template></ProjectDialog></template>
