<script setup lang="ts">
import { onMounted,ref,watch } from 'vue'
import ProjectDialog from './ProjectDialog.vue'
import type { ProjectItem,ProjectMovePlan } from '@/types/project'
const props=defineProps<{item:ProjectItem}>(),emit=defineEmits<{close:[];moved:[warnings:string[]]}>()
const parent=ref(''),name=ref(''),keepLink=ref(true),busy=ref(false),error=ref(''),token=ref(''),plan=ref<ProjectMovePlan|null>(null),acknowledged=ref(false)
watch([parent,name,keepLink],()=>{token.value='';plan.value=null;acknowledged.value=false})
async function pick(){busy.value=true;error.value='';try{const result=await window.baoyi.project.prepareMove(props.item.id);if(result){parent.value=result.destinationParent;name.value=result.name}}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
onMounted(()=>void pick())
async function preview(){busy.value=true;error.value='';try{if(!name.value.trim()||/[\\/]/.test(name.value))throw new Error('请输入单个文件夹或文件名称');const result=await window.baoyi.project.previewMove(props.item.id,parent.value.replace(/[\\/]$/,'')+'\\'+name.value,keepLink.value);token.value=result.token;plan.value=result.plan}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function move(){busy.value=true;error.value='';try{const result=await window.baoyi.project.move(token.value);emit('moved',result.warnings);emit('close')}catch(e){error.value=(e as Error).message;token.value='';plan.value=null}finally{busy.value=false}}
</script>
<template><ProjectDialog title="移动项目" :busy="busy" @close="emit('close')"><p class="pj-muted">将项目主目录或主文件移到新位置，并更新抱一中的关联路径。</p><label class="pj-field">当前位置<span class="pj-path">{{item.path}}</span></label><label class="pj-field">目标父目录<div class="pj-inline"><input v-model="parent" readonly placeholder="选择目标文件夹"/><button class="pj-button" :disabled="busy" @click="pick">选择</button></div></label><label class="pj-field">移动后的名称<input v-model="name" :disabled="busy" maxlength="180"/></label><label class="pj-check"><input v-model="keepLink" type="checkbox" :disabled="busy"/>保留旧位置入口，让已有笔记和快捷方式继续访问</label><p class="pj-muted">此选项适用于目录。项目源码与笔记正文保持原内容。</p>
<div v-if="plan" class="pj-move-preview"><strong>移动到</strong><p class="pj-path">{{plan.destination}}</p><p>更新 {{plan.affected}} 项已登记资源的位置；{{plan.externalEntries}} 个外部入口保持原位。</p><ul><li v-for="warning in plan.warnings" :key="warning">{{warning}}</li></ul><label class="pj-check"><input v-model="acknowledged" type="checkbox" :disabled="busy"/>我已关闭此项目相关程序，并核对移动范围</label></div><p v-if="busy" role="status">正在处理文件，请保持窗口打开…</p><p v-if="error" class="pj-error" role="alert">{{error}}</p><template #footer><button class="pj-button" :disabled="busy" @click="emit('close')">取消</button><button v-if="!token" class="pj-button pj-primary" :disabled="busy||!parent||!name" @click="preview">预览移动</button><button v-else class="pj-button pj-primary" :disabled="busy||!acknowledged" @click="move">确认移动</button></template></ProjectDialog></template>
