<script setup lang="ts">
import { onMounted,ref } from 'vue'
import {useProjectStore} from '@/stores/project'
import ProjectDialog from './ProjectDialog.vue'
import { type ProjectItem } from '@/types/project'
const store=useProjectStore();onMounted(()=>void store.refresh())
const props=defineProps<{item:ProjectItem}>(),emit=defineEmits<{close:[];saved:[]}>()
const model=ref({name:props.item.name,summary:props.item.summary,category:props.item.category,source:props.item.source,state:props.item.state,group:props.item.group,pinned:props.item.pinned,notes:props.item.notes,defaultEntryId:props.item.defaultEntryId}),tags=ref(props.item.tags.join('，')),busy=ref(false),error=ref('')
async function save(){busy.value=true;error.value='';try{await window.baoyi.project.update(props.item.id,{...model.value,tags:tags.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean)});emit('saved');emit('close')}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
</script>
<template><ProjectDialog title="编辑项目" :busy="busy" @close="emit('close')"><form id="project-edit" class="pj-form" @submit.prevent="save"><label class="pj-field">项目名称<input v-model="model.name" required maxlength="160"/></label><label class="pj-field">简介<textarea v-model="model.summary" rows="3" maxlength="4000"/></label><div class="pj-form-pair"><label class="pj-field">类型<select v-model="model.category" aria-label="类型"><option v-for="c in store.categories" :key="c">{{c}}</option></select></label><label class="pj-field">来源<select v-model="model.source" aria-label="来源"><option value="unknown">未标记</option><option value="self">自己建立</option><option value="third-party">第三方项目</option><option value="mixed">混合来源</option></select></label></div><div class="pj-form-pair"><label class="pj-field">状态<select v-model="model.state" aria-label="状态"><option value="active">使用中</option><option value="maintaining">维护中</option><option value="paused">已暂停</option><option value="archived">已归档</option></select></label><label class="pj-field">分组<input v-model="model.group" maxlength="100" placeholder="例如：工作、兴趣、自用工具"/></label></div><label class="pj-field">标签<input v-model="tags" placeholder="用逗号分隔"/></label><label class="pj-field">默认入口<select v-model="model.defaultEntryId" aria-label="默认入口"><option value="">未设置</option><option v-for="e in item.entries" :key="e.id" :value="e.id">{{e.label}}</option></select></label><label class="pj-field">备注<textarea v-model="model.notes" rows="4" maxlength="20000" placeholder="记录项目用途、注意事项或下次准备做什么…"/></label><label class="pj-check"><input v-model="model.pinned" type="checkbox"/>置顶这个项目</label><p v-if="error" class="pj-error" role="alert">{{error}}</p></form><template #footer><button class="pj-button" :disabled="busy" @click="emit('close')">取消</button><button form="project-edit" class="pj-button pj-primary" :disabled="busy" type="submit">保存</button></template></ProjectDialog></template>
