<script setup lang="ts">
import { onBeforeUnmount,ref,watch } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowLeft,ArrowUpRight,FolderOpen,FolderInput,Plus,Pencil,Star,Trash2,RefreshCw,FileText,Link,Code2,FolderKanban } from 'lucide-vue-next'
import { useToast } from '@/composables/useToast'
import type { ProjectCandidate,ProjectEntry,ProjectItem } from '@/types/project'
import ProjectWorkbench from '@/components/project/ProjectWorkbench.vue'
import ProjectDialog from '@/components/project/ProjectDialog.vue'
import ProjectEdit from '@/components/project/ProjectEdit.vue'
import ProjectEntryEditor from '@/components/project/ProjectEntryEditor.vue'
import ProjectMove from '@/components/project/ProjectMove.vue'
import '@/styles/project.css'
const projectApi=window.baoyi.project
const props=defineProps<{id:string}>(),router=useRouter(),{error:toastError,success}=useToast(),item=ref<ProjectItem|null>(null),error=ref(''),edit=ref(false),entryEditor=ref(false),entry=ref<ProjectEntry>(),moving=ref(false),busy=ref(false),scan=ref<ProjectCandidate|null>(null)
const sourceNames:Record<string,string>={self:'自己建立','third-party':'第三方项目',mixed:'混合来源',unknown:'来源未标记'},stateNames:Record<string,string>={active:'使用中',maintaining:'维护中',paused:'已暂停',archived:'已归档'}
async function load(){try{item.value=await projectApi.get(props.id);error.value=item.value?'':'找不到这个项目'}catch(e){error.value=(e as Error).message}}
watch(()=>props.id,()=>void load(),{immediate:true})
const unsubscribe=projectApi.onChanged(()=>void load());onBeforeUnmount(unsubscribe)
async function action(fn:()=>Promise<unknown>){busy.value=true;try{await fn();await load()}catch(e){toastError((e as Error).message)}finally{busy.value=false}}
function editEntry(e?:ProjectEntry){entry.value=e;entryEditor.value=true}
async function removeEntry(e:ProjectEntry){if(!item.value||!confirm(`移除入口“${e.label}”？原文件保留。`))return;const entries=item.value.entries.filter(x=>x.id!==e.id);await action(()=>projectApi.update(props.id,JSON.parse(JSON.stringify({entries,defaultEntryId:item.value!.defaultEntryId===e.id?entries[0]?.id||'':item.value!.defaultEntryId}))))}
async function remove(){if(!item.value||!confirm(`从抱一中移除“${item.value.name}”？项目文件保留在原位置。`))return;await action(async()=>{await projectApi.remove(props.id);await router.push('/project')})}
async function rescan(){await action(async()=>{scan.value=await projectApi.rescan(props.id)})}
async function acceptScan(){if(!item.value||!scan.value)return;const paths=new Set(item.value.entries.map(e=>e.path.toLowerCase())),added=scan.value.entries.filter(e=>!paths.has(e.path.toLowerCase()));await action(()=>projectApi.update(props.id,JSON.parse(JSON.stringify({entries:[...item.value!.entries,...added].slice(0,100)}))));scan.value=null}
function moved(warnings:string[]){if(warnings.length)toastError(warnings.join('\n'));else success('项目已移动，关联路径已更新');void load()}
</script>
<template><main class="pj-detail project-detail-tabs"><button class="pj-back" @click="router.push('/project')"><ArrowLeft :size="17"/>项目库</button><p v-if="error" class="pj-error" role="alert">{{error}}</p><template v-if="item"><header class="pj-detail-header"><div class="pj-project-symbol pj-symbol-large"><FolderKanban :size="34"/></div><div class="pj-detail-title"><div class="pj-tags"><span>{{item.category}}</span><span>{{sourceNames[item.source]}}</span><span>{{stateNames[item.state]}}</span><span v-if="item.version">v{{item.version}}</span></div><h1>{{item.name}}</h1><p>{{item.summary||'为项目添加一句简介，方便下次找回。'}}</p></div><button class="pj-icon" aria-label="编辑项目" @click="edit=true"><Pencil :size="20"/></button></header>
<div class="pj-detail-actions"><button class="pj-button pj-primary" :disabled="busy" @click="action(()=>projectApi.open(id))"><ArrowUpRight :size="18"/>{{item.entries.find(e=>e.id===item!.defaultEntryId)?.label||'打开项目'}}</button><button class="pj-button" @click="action(()=>projectApi.reveal(id))"><FolderOpen :size="17"/>定位文件</button><button class="pj-button" :disabled="busy" @click="moving=true"><FolderInput :size="17"/>移动项目</button><button class="pj-button" :disabled="busy" @click="rescan"><RefreshCw :size="16"/>刷新入口候选</button></div>
<div v-if="!item.available" class="pj-error">项目位置失效。<button class="pj-button" @click="action(()=>projectApi.relocate(id))">重新定位</button></div>
<ProjectWorkbench :key="item.id" :item="item" @updated="load"><template #entries><section class="pj-section"><header><div><h2>项目入口</h2><p>在熟悉的工具中继续工作</p></div><button class="pj-button" @click="editEntry()"><Plus :size="16"/>添加入口</button></header><div class="pj-entries"><article v-for="e in item.entries" :key="e.id" class="pj-entry"><div class="pj-entry-icon"><Link v-if="e.type==='url'" :size="20"/><Code2 v-else-if="e.type==='command'" :size="20"/><FileText v-else :size="20"/></div><button class="pj-entry-main" :disabled="busy" @click="action(()=>projectApi.open(id,e.id))"><strong>{{e.label}}<Star v-if="e.id===item.defaultEntryId" :size="12"/></strong><span>{{e.role}} · {{e.path}}</span></button><button class="pj-icon" :aria-label="'编辑入口 '+e.label" @click="editEntry(e)"><Pencil :size="15"/></button><button class="pj-icon" :aria-label="'移除入口 '+e.label" @click="removeEntry(e)"><Trash2 :size="15"/></button></article></div></section><section class="pj-section"><header><h2>项目备注</h2><button class="pj-icon" aria-label="编辑备注" @click="edit=true"><Pencil :size="16"/></button></header><p class="pj-notes">{{item.notes||'记录用途、注意事项，或留下一句下次要做的事。'}}</p></section></template><template #info><aside class="pj-properties"><h2>项目资料</h2><dl><dt>主位置</dt><dd class="pj-path">{{item.path}}</dd><dt>分组</dt><dd>{{item.group||'未分组'}}</dd><dt>标签</dt><dd>{{item.tags.join(' · ')||'未添加'}}</dd><dt>识别依据</dt><dd>{{item.evidence||'手动登记'}}</dd><dt>最近通过抱一打开</dt><dd>{{item.lastOpenedAt?new Date(item.lastOpenedAt).toLocaleString():'尚未打开'}}</dd><dt>登记时间</dt><dd>{{new Date(item.createdAt).toLocaleDateString()}}</dd></dl><button class="pj-button pj-danger" @click="remove"><Trash2 :size="15"/>移除项目索引</button></aside></template></ProjectWorkbench>
<ProjectEdit v-if="edit" :item="item" @close="edit=false" @saved="load"/><ProjectEntryEditor v-if="entryEditor" :item="item" :entry="entry" @close="entryEditor=false" @saved="load"/><ProjectMove v-if="moving" :item="item" @close="moving=false" @moved="moved"/>
<ProjectDialog v-if="scan" title="发现的项目入口" :busy="busy" @close="scan=null"><p class="pj-muted">扫描依据：{{scan.evidence}}。保留已设置的名称、状态和默认入口，只补充新发现的位置。</p><ul><li v-for="e in scan.entries.filter(e=>!item!.entries.some(x=>x.path.toLowerCase()===e.path.toLowerCase()))" :key="e.id">{{e.label}}</li></ul><template #footer><button class="pj-button" :disabled="busy" @click="scan=null">取消</button><button class="pj-button pj-primary" :disabled="busy" @click="acceptScan">补充新入口</button></template></ProjectDialog></template></main></template>
