/** Local-only sample server. Media was generated by the isolated desktop test. */
const fs = require('node:fs')
const path = require('node:path')
const http = require('node:http')
const root = __dirname
const catalogue = JSON.parse(fs.readFileSync(path.join(root, 'catalogue.json'), 'utf8'))
const video = fs.readFileSync(path.join(root, 'assets', 'sample.webm'))
const posters = catalogue.entries.map((_, i) => fs.readFileSync(path.join(root, 'assets', `poster-${i}.png`)))
const server = http.createServer((request, response) => {
  const pathname = new URL(request.url, 'http://127.0.0.1').pathname
  const poster = /^\/poster\/(\d+)\.png$/.exec(pathname)
  if (poster && posters[Number(poster[1])]) {
    response.writeHead(200, { 'Content-Type': 'image/png' }); response.end(posters[Number(poster[1])]); return
  }
  if (pathname === '/sample.webm') {
    response.setHeader('Content-Type', 'video/webm'); response.setHeader('Accept-Ranges', 'bytes')
    const range = /^bytes=(\d+)-(\d*)$/.exec(request.headers.range || '')
    if (range) {
      const start = Number(range[1]), end = Math.min(range[2] ? Number(range[2]) : video.length - 1, video.length - 1)
      if (start > end) { response.writeHead(416, { 'Content-Range': `bytes */${video.length}` }); response.end(); return }
      response.writeHead(206, { 'Content-Range': `bytes ${start}-${end}/${video.length}`, 'Content-Length': end - start + 1 }); response.end(video.subarray(start, end + 1)); return
    }
    response.setHeader('Content-Length', video.length); response.end(video); return
  }
  if (pathname.startsWith('/watch/') || pathname === '/') {
    response.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' })
    response.end('<!doctype html><html lang="zh"><head><meta charset="utf-8"><title>本机测试影像</title></head><body style="background:#161922;color:#eee;font-family:sans-serif;padding:32px"><h1>本机测试影像</h1><p>此短片由程序绘制，只用于验证播放与下载。</p><video width="640" controls autoplay muted loop src="/sample.webm"></video></body></html>'); return
  }
  response.writeHead(404); response.end('Not found')
})
server.listen(0, '127.0.0.1', () => {
  const base = `http://127.0.0.1:${server.address().port}`
  const source = { ...catalogue, homeUrl: base, entries: catalogue.entries.map((entry, i) => ({ ...entry,
    coverUrl: `${base}/poster/${i}.png`, pageUrl: `${base}/watch/${entry.id}`, playUrl: `${base}/watch/${entry.id}`,
    downloads: [{ label: '测试短片', url: `${base}/sample.webm` }] })) }
  const file = path.join(root, 'localhost-catalogue.json')
  fs.writeFileSync(file, JSON.stringify(source, null, 2))
  console.log(`本机演示已就绪：${base}\n\n在抱一「影视库 → 找视频」中导入：\n${file}\n\n保持此窗口打开；按 Ctrl+C 结束。每次启动后请重新导入生成的目录。`)
})
