<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {Music2,Play,Pause,SkipBack,SkipForward,FolderOpen} from 'lucide-vue-next'
import type {VideoItem} from '@/types'
import type {AudioMetadata} from '@/utils/audio'
const props=defineProps<{items:VideoItem[]}>(),emit=defineEmits<{open:[item:VideoItem]}>()
interface Track {id:string;resource:VideoItem;title:string;duration:number;episode:string}
const tracks=ref<Track[]>([]),current=ref<Track|null>(null),player=ref<HTMLAudioElement>(),failure=ref(''),music=ref<AudioMetadata|null>(null),playing=ref(false)
const source=computed(()=>current.value?`baoyi://audio/${current.value.resource.id}/${current.value.episode}`:'')
let revision=0
watch(()=>props.items,async items=>{const round=++revision;const rows:Track[]=[];for(const item of items){try{const library=await window.baoyi.video.library(item.id);if(round!==revision)return;if(library.contents.length){for(const ep of library.contents)rows.push({id:ep.id,resource:item,title:ep.title,episode:ep.id,duration:ep.duration_sec})}else rows.push({id:item.id,resource:item,title:item.name_zh||item.file_name,episode:'',duration:item.duration_sec})}catch{failure.value='部分曲目暂时无法读取，请刷新重试'}}tracks.value=rows;if(current.value&&!rows.some(t=>t.id===current.value!.id)){player.value?.pause();current.value=null}},{immediate:true})
function duration(seconds:number){return seconds?`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`:'—'}
async function play(track:Track){if(current.value?.id===track.id&&player.value){if(player.value.paused)await loaded();else player.value.pause();return}failure.value='';music.value=null;current.value=track;try{const res=await fetch(`baoyi://audio/${track.resource.id}/${track.episode}?info=1`);if(current.value?.id===track.id&&res.ok)music.value=(await res.json())?.music||null}catch{}}
function next(delta=1){const index=tracks.value.findIndex(t=>t.id===current.value?.id),track=tracks.value[index+delta];if(track)void play(track)}
async function loaded(){if(current.value&&player.value&&Number.isFinite(player.value.duration))current.value.duration=player.value.duration;try{await player.value?.play()}catch{failure.value='无法自动播放，请点击播放按钮；不支持的格式可用系统播放器打开。'}}
</script>
<template><div class="audio-library"><header><div class="audio-disc"><Music2 :size="34"/></div><div><span class="audio-eyebrow">音乐 · 播客 · 有声书</span><h2>我的音频</h2><p>{{items.length}} 个专辑或文件夹 · {{tracks.length}} 首曲目</p></div></header><p v-if="!tracks.length">选择「导入音频」，添加本地专辑、播客或有声书。</p><p v-if="failure" class="audio-error" role="alert">{{failure}}<button v-if="current" @click="emit('open',current.resource)">打开详情</button></p><div class="audio-table"><div class="audio-row audio-head"><span>#</span><span>曲目</span><span>专辑 / 文件夹</span><span>时长</span><span/></div><div v-for="(track,i) in tracks" :key="track.id" class="audio-row" :class="{current:current?.id===track.id}"><button :aria-label="'播放 '+track.title" @click="play(track)"><Pause v-if="current?.id===track.id && playing" :size="15"/><Play v-else-if="current?.id===track.id" :size="15"/><span v-else>{{i+1}}</span></button><button class="audio-name" @click="play(track)">{{track.title}}</button><button class="audio-album" @click="emit('open',track.resource)">{{track.resource.name_zh||track.resource.file_name}}</button><span>{{duration(track.duration)}}</span><button :aria-label="'查看 '+track.title" @click="emit('open',track.resource)"><FolderOpen :size="15"/></button></div></div><div v-if="current" class="audio-player"><Music2 :size="26"/><div class="audio-now"><strong>{{current.title}}</strong><span>{{[music?.artist,music?.album].filter(Boolean).join(' · ')||current.resource.name_zh}}</span><small>{{[music?.sampleRate ? music.sampleRate/1000+' kHz':'',music?.bitDepth ? music.bitDepth+' bit':'',music?.bitRate ? Math.round(music.bitRate/1000)+' kbps':''].filter(Boolean).join(' · ')}}</small></div><button aria-label="上一曲" :disabled="tracks[0]?.id===current.id" @click="next(-1)"><SkipBack :size="18"/></button><audio ref="player" :src="source" controls preload="metadata" @loadedmetadata="loaded" @play="playing=true" @pause="playing=false" @ended="next()" @error="failure='此文件无法内置播放，可在详情中使用系统播放器打开。'"/><button aria-label="下一曲" :disabled="tracks[tracks.length-1]?.id===current.id" @click="next()"><SkipForward :size="18"/></button></div></div></template>
<style scoped>.audio-library{padding:10px 6px 0}.audio-library>header{display:flex;gap:22px;align-items:center;margin-bottom:30px}.audio-disc{width:94px;height:94px;border-radius:50%;display:grid;place-items:center;border:14px double var(--divider);background:var(--active-surface);color:var(--accent)}.audio-eyebrow{font-size:11px;letter-spacing:2px;color:var(--text-sub)}.audio-library h2{font-size:27px;margin:8px 0}.audio-library p{font-size:12px;color:var(--text-sub)}.audio-table{border-top:1px solid var(--divider);padding-bottom:140px}.audio-row{display:grid;grid-template-columns:35px minmax(180px,2fr) minmax(140px,1fr) 65px 30px;align-items:center;gap:15px;padding:13px 10px;border-bottom:1px solid var(--divider);font-size:13px}.audio-row.current{background:var(--active-surface);color:var(--accent)}.audio-row button{text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.audio-head{font-size:11px;color:var(--text-faint);padding-block:15px}.audio-album,.audio-row>span{color:var(--text-sub)}.audio-name{font-weight:500}.audio-player{position:sticky;bottom:0;display:flex;align-items:center;gap:14px;padding:18px;background:var(--bg-card);border:1px solid var(--divider);border-radius:10px;box-shadow:0 -8px 24px #0001}.audio-now{display:grid;gap:5px;min-width:0;flex:1}.audio-now strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.audio-now span,.audio-now small{font-size:11px;color:var(--text-sub)}audio{width:300px;max-width:40%}.audio-error{color:var(--danger)!important}.audio-error button{margin-left:12px;text-decoration:underline}</style>
