/** Reader rehearsal with real IPC and disposable media/profile. */
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { DatabaseSync } from 'node:sqlite'
import { initSchema } from '../electron/services/schema.ts'
import { KINDS } from '../electron/kinds/index.ts'
import { ImageLibrary } from '../electron/kinds/image/library.ts'
import { scanImageImport } from '../electron/kinds/image/scanner.ts'
import { pngImage } from './helpers/test-images.ts'
const require = createRequire(import.meta.url)
const { _electron } = require(process.env.BAOYI_PLAYWRIGHT || 'C:/Users/yicha/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
const packedExecutable = process.argv[2]
const executable = path.resolve(packedExecutable || 'node_modules/electron/dist/electron.exe')
const output = path.resolve('output/image-optimization/reader-ui' + (packedExecutable ? '-packaged' : '')); fs.mkdirSync(output, { recursive: true })
const profile = fs.mkdtempSync(path.join(output, 'profile-'))
const db = new DatabaseSync(path.join(profile, 'baoyi.db')); db.exec('PRAGMA foreign_keys=ON'); initSchema(db, KINDS)
for (const [key, value] of Object.entries({ onboarded: true, theme: 'dark', hanime_builtin_hosts: false })) db.prepare('INSERT OR REPLACE INTO settings(key,value) VALUES(?,?)').run(key, JSON.stringify(value))
const library = new ImageLibrary(db), ids: string[] = []
for (const name of ['reader-one', 'reader-two']) {
  const root = path.join(profile, name)
  for (let c = 1; c <= 2; c++) {
    const directory = path.join(root, 'chapter-' + c); fs.mkdirSync(directory, { recursive: true })
    for (let n = 1; n <= (c === 1 ? 6 : 3); n++) fs.writeFileSync(path.join(directory, n + '.png'), pngImage(800, 1200, [40 + n * 20, 80, 90 + c * 40]))
  }
  ids.push(library.register((await scanImageImport(root, 'comic', false))[0]).id)
}
db.close()
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE; delete env.VITE_DEV_SERVER_URL
const launch = () => _electron.launch({ executablePath: executable, args: [...(packedExecutable ? [] : [path.resolve('.')]), '--user-data-dir=' + profile, '--disable-gpu'], env })
let app = await launch()
const errors: string[] = [], checks: string[] = []
try {
  const page = await app.firstWindow(); page.setDefaultTimeout(8000); page.on('pageerror', (e: Error) => errors.push(e.message))
  await page.waitForFunction(() => !!window.baoyi?.image)
  await app.evaluate(({ BrowserWindow }: any) => BrowserWindow.getAllWindows()[0].setSize(1440, 900))
  await page.evaluate((id: string) => { location.hash = '/image/' + id }, ids[0])
  await page.getByRole('button', { name: '开始阅读', exact: true }).click()
  await page.getByLabel('放大图片', { exact: true }).waitFor()
  assert.equal(await page.locator('.image-reader').getAttribute('aria-modal'),'false')
  await page.getByRole('button',{name:/^软件\s/}).click()
  await page.waitForFunction(()=>location.hash==='#/')
  assert.equal(await page.locator('.image-reader').count(),1,'reader survives module navigation')
  await page.keyboard.press('Escape')
  assert.equal(await page.locator('.image-reader').count(),1,'background keys do not close reader')
  await page.getByLabel('收起阅读器',{exact:true}).click()
  assert.equal(await page.locator('.reader-viewport').isVisible(),false)
  await page.getByLabel('展开阅读器',{exact:true}).click()
  const initialBox=await page.locator('.image-reader').boundingBox()
  const titleBox=await page.locator('.reader-title strong').boundingBox()
  await page.mouse.move(titleBox.x+30,titleBox.y+10);await page.mouse.down();await page.mouse.move(titleBox.x-60,titleBox.y+25);await page.mouse.up()
  assert.ok((await page.locator('.image-reader').boundingBox()).x<initialBox.x-40)
  await page.getByLabel('最大化阅读窗口',{exact:true}).click()
  assert.ok((await page.locator('.image-reader').boundingBox()).width>initialBox.width)
  await page.getByLabel('还原阅读窗口',{exact:true}).click()
  await page.getByLabel('全屏阅读',{exact:true}).click()
  await page.waitForFunction(()=>!!document.fullscreenElement)
  await page.waitForFunction(()=>{const picture=document.querySelector('.reader-sheet img')?.getBoundingClientRect(),viewport=document.querySelector('.reader-viewport')?.getBoundingClientRect();return picture&&viewport&&picture.top>=viewport.top&&picture.bottom<=viewport.bottom+1})
  const rails=await page.evaluate(()=>{const view=document.querySelector('.reader-viewport')!.getBoundingClientRect(),left=document.querySelector('.reader-tools')!.getBoundingClientRect(),right=document.querySelector('.reader-bottom')!.getBoundingClientRect();return left.right<=view.left+1&&right.left>=view.right-1});assert.equal(rails,true)
  await page.getByLabel('全屏阅读',{exact:true}).click();await page.waitForFunction(()=>!document.fullscreenElement)
  await page.evaluate((id:string)=>{location.hash='/image/'+id},ids[0])
  await page.getByRole('button',{name:/^(开始阅读|继续阅读)$/}).waitFor()
  checks.push('nonmodal-module-navigation-minimize-drag-maximize')
  const current = async (n: number) => page.waitForFunction((n: number) => document.querySelector('.reader-bottom span')?.textContent?.includes(n + ' / 9'), n)
  await page.getByLabel('双页阅读', { exact: true }).click(); await current(1)
  assert.equal(await page.locator('.reader-sheet').count(), 1)
  await page.getByLabel('后一页', { exact: true }).click(); await current(2)
  assert.equal(await page.locator('.reader-sheet').count(), 2)
  await page.screenshot({ path: path.join(output, 'spread-1440.png') })
  await page.getByLabel('后一页', { exact: true }).click(); await current(4)
  await page.getByLabel('后一页', { exact: true }).click(); await current(6)
  assert.equal(await page.locator('.reader-sheet').count(), 1)
  await page.getByLabel('后一页', { exact: true }).click(); await current(7)
  assert.equal(await page.locator('.reader-sheet').count(), 2)
  await page.getByLabel('前一页', { exact: true }).click(); await current(6)
  checks.push('cover-and-chapter-spreads')
  await page.getByLabel('放大图片', { exact: true }).click()
  await page.waitForFunction(() => document.querySelector('[aria-label="缩放比例"]')?.textContent === '125%')
  await page.getByLabel('阅读设置', { exact: true }).click()
  await page.getByLabel('图片缩放', { exact: true }).selectOption('original')
  await page.getByLabel('阅读设置', { exact: true }).click()
  await page.waitForFunction(() => (document.querySelector('.reader-sheet img') as HTMLImageElement)?.naturalWidth === 800)
  const canvas = page.locator('.reader-spread'), before = await canvas.boundingBox(), box = await page.locator('.reader-viewport').boundingBox()
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 - 70, box.y + box.height / 2 - 80, { steps: 8 }); await page.mouse.up()
  await page.waitForFunction((y: number) => Math.abs(document.querySelector('.reader-spread')!.getBoundingClientRect().y - y) > 30, before.y)
  await page.getByLabel('旋转图片', { exact: true }).click()
  await page.waitForFunction(() => (document.querySelector('.reader-sheet') as HTMLElement)?.style.width === '1200px')
  await page.getByLabel('重置缩放', { exact: true }).click()
  await page.waitForFunction(() => document.querySelector('[aria-label="缩放比例"]')?.textContent === '100%')
  checks.push('zoom-drag-rotate-reset')
  await page.getByLabel('阅读设置', { exact: true }).click()
  await page.getByLabel('图片缩放', { exact: true }).selectOption('screen')
  await page.getByLabel('阅读方向', { exact: true }).selectOption('rtl')
  await page.getByLabel('封面独立成页', { exact: true }).uncheck()
  await current(5)
  await page.getByLabel('阅读设置', { exact: true }).click()
  await page.keyboard.press('ArrowLeft'); await current(7)
  await page.keyboard.press('ArrowRight'); await current(5)
  for (let i = 0; i < 3; i++) await page.getByLabel('缩小图片', { exact: true }).click()
  await page.waitForFunction(() => document.querySelector('[aria-label="缩放比例"]')?.textContent === '25%')
  assert.equal(await page.getByLabel('缩小图片', { exact: true }).isDisabled(), true)
  const fitted = await canvas.boundingBox()
  assert.ok(fitted.width < box.width && fitted.height < box.height, '25% must not be forced back to fill the viewport')
  for (let i = 0; i < 15; i++) await page.getByLabel('放大图片', { exact: true }).click()
  await page.waitForFunction(() => document.querySelector('[aria-label="缩放比例"]')?.textContent === '400%')
  assert.equal(await page.getByLabel('放大图片', { exact: true }).isDisabled(), true)
  await page.getByLabel('重置缩放', { exact: true }).click()
  await page.getByLabel('阅读设置', { exact: true }).click()
  await page.getByLabel('封面独立成页', { exact: true }).check()
  await page.getByLabel('阅读方向', { exact: true }).selectOption('ltr')
  await page.getByLabel('阅读设置', { exact: true }).click()
  await page.getByLabel('后一页', { exact: true }).click(); await current(6)
  checks.push('zoom-limits-rtl-and-cover-toggle')
  await page.getByLabel('添加书签', { exact: true }).click()
  await page.getByLabel('书签列表', { exact: true }).click()
  await page.getByLabel('书签名称', { exact: true }).fill('Remember this page')
  await page.getByLabel('书签名称', { exact: true }).press('Tab')
  await page.waitForFunction(async (id: string) => (await window.baoyi.image.bookmarks(id))[0]?.label === 'Remember this page', ids[0])
  await page.getByLabel('标记为已读', { exact: true }).click()
  await page.waitForFunction(async (id: string) => (await window.baoyi.image.get(id))?.read, ids[0])
  await page.screenshot({ path: path.join(output, 'reader-1440.png') })
  await page.getByLabel('书签列表', { exact: true }).click()
  await page.getByLabel('连续阅读', { exact: true }).click()
  await page.locator('.reader-viewport').evaluate((el: HTMLElement) => { el.scrollTop += 220 })
  await page.getByLabel('移除当前书签', { exact: true }).click()
  await page.getByLabel('添加书签', { exact: true }).click()
  const saved = await page.evaluate(async (id: string) => (await window.baoyi.image.bookmarks(id))[0], ids[0]); assert.ok(saved.offset > 0.1)
  await page.getByLabel('放大图片', { exact: true }).click()
  const position = await page.locator('.reader-viewport').evaluate((el: HTMLElement) => el.scrollTop)
  const stripBox = await page.locator('.reader-viewport').boundingBox()
  await page.mouse.move(stripBox.x + 100, stripBox.y + 250); await page.mouse.down(); await page.mouse.move(stripBox.x + 100, stripBox.y + 160, { steps: 5 }); await page.mouse.up()
  assert.ok(await page.locator('.reader-viewport').evaluate((el: HTMLElement) => el.scrollTop) > position + 50)
  assert.ok(await page.locator('.reader-strip-page img').count() <= 7)
  await page.getByLabel('阅读设置', { exact: true }).click()
  await page.getByRole('button', { name: '设为全局默认', exact: true }).click()
  await page.waitForFunction(async () => (await window.baoyi.image.preferences()).zoom === 1.25)
  await page.getByLabel('单页阅读', { exact: true }).click()
  await page.getByLabel('阅读设置', { exact: true }).click()
  await page.getByLabel('书签列表', { exact: true }).click()
  await page.getByRole('button', { name: '跳转到第 6 页', exact: true }).click(); await current(6)
  await app.evaluate(({ BrowserWindow }: any) => BrowserWindow.getAllWindows()[0].setSize(960, 640))
  await page.screenshot({ path: path.join(output, 'reader-960.png') })
  assert.equal(await page.locator('.reader-tools').evaluate((el: HTMLElement) => el.scrollWidth > el.clientWidth), false)
  const overlap = await page.evaluate(() => { const a = document.querySelector('.reader-viewport')!.getBoundingClientRect(), b = document.querySelector('.reader-panel')!.getBoundingClientRect(); return a.right > b.left + 1 }); assert.equal(overlap, false)
  await page.getByLabel('关闭阅读器', { exact: true }).click()
  assert.equal(await page.getByLabel('已读', { exact: true }).isChecked(), true)
  const state = await page.evaluate(async (id: string) => window.baoyi.image.readerPreferences(id), ids[0]); assert.equal(state.customized, true); assert.equal(state.preferences.mode, 'single')
  const other = await page.evaluate(async (id: string) => window.baoyi.image.readerPreferences(id), ids[1]); assert.equal(other.customized, false); assert.equal(other.preferences.mode, 'scroll')
  await page.getByRole('button', { name: '继续阅读', exact: true }).click(); await page.getByLabel('阅读设置', { exact: true }).click()
  await page.getByRole('button', { name: '使用全局默认', exact: true }).click()
  await page.waitForFunction(async (id: string) => !(await window.baoyi.image.readerPreferences(id)).customized, ids[0])
  await page.getByLabel('关闭阅读器', { exact: true }).click()
  checks.push('bookmarks-offsets-settings-isolation-read-status-and-responsive-layout')
  await app.close(); app = await launch()
  const restarted = await app.firstWindow(); await restarted.waitForFunction(() => !!window.baoyi?.image)
  const result = await restarted.evaluate(async (id: string) => ({ bookmarks: await window.baoyi.image.bookmarks(id), item: await window.baoyi.image.get(id), preferences: await window.baoyi.image.readerPreferences(id) }), ids[0])
  assert.equal(result.bookmarks[0].offset, saved.offset); assert.equal(result.item.read, true); assert.equal(result.item.publication, 'unknown')
  assert.equal(result.preferences.customized, false, 'closing the reader must not undo the explicit reset to global defaults')
  assert.deepEqual(errors, []); checks.push('restart-persistence')
  fs.writeFileSync(path.join(output, 'report.json'), JSON.stringify({ checks, errors, profile }, null, 2)); console.log('PASS ' + checks.join(', '))
} catch (cause) {
  const page = await app.firstWindow()
  console.error(await page.locator('.image-reader').innerText())
  console.error(errors)
  await page.screenshot({ path: path.join(output, 'failure.png') })
  throw cause
} finally { await app.close() }
