<script setup lang="ts">
import { onMounted,ref } from 'vue'
import { X, Search, ArrowLeft, Download } from 'lucide-vue-next'
import { useImageStore } from '@/stores/image'
import ImageDownloadList from './ImageDownloadList.vue'
import type { ImageSourceWork,ImageSourceChapter } from '@/types/image'
const emit=defineEmits<{close:[]}>(),store=useImageStore(),logged=ref(false),account=ref(''),password=ref(''),busy=ref(false),error=ref(''),query=ref(''),page=ref(1),total=ref(0)
const results=ref<ImageSourceWork[]>([]),detail=ref<{work:ImageSourceWork;chapters:ImageSourceChapter[]}|null>(null),selected=ref<string[]>([]),group=ref(''),message=ref('')
async function login(){busy.value=true;error.value='';try{await window.baoyi.image.sourceLogin(account.value,password.value);logged.value=true}catch(cause){error.value=(cause as Error).message}finally{password.value='';busy.value=false}}
async function logout(){await window.baoyi.image.sourceLogout();logged.value=false;results.value=[];detail.value=null}
async function search(at=1){busy.value=true;error.value='';detail.value=null;try{const response=await window.baoyi.image.sourceSearch(query.value,at);results.value=response.items;page.value=at;total.value=response.pages}catch(cause){error.value=(cause as Error).message}finally{busy.value=false}}
async function open(work:ImageSourceWork){busy.value=true;error.value='';try{detail.value=await window.baoyi.image.sourceDetail(work.id);selected.value=detail.value.chapters.map(c=>c.id)}catch(cause){error.value=(cause as Error).message}finally{busy.value=false}}
async function download(){if(!detail.value)return;busy.value=true;error.value='';try{const job=await window.baoyi.image.download(detail.value.work.id,[...selected.value],group.value||null);if(job)message.value='已加入下载队列。完成后会自动加入漫画书架。'}catch(cause){error.value=(cause as Error).message}finally{busy.value=false}}
onMounted(async()=>{try{logged.value=await window.baoyi.image.sourceStatus()}catch(cause){error.value=(cause as Error).message}})
</script>
<template><Teleport to="body"><div class="im-overlay" @click.self="!busy&&emit('close')"><section class="im-dialog source-dialog" role="dialog" aria-modal="true" aria-label="从哔咔添加"><header><div><h2>从哔咔添加</h2><p>选好章节，下载到本地后阅读。</p></div><button class="im-icon" aria-label="关闭哔咔" @click="emit('close')"><X :size="20"/></button></header>
  <form v-if="!logged" class="source-login" @submit.prevent="login"><label class="im-field">用户名<input v-model="account" type="text" autocomplete="username" required/></label><label class="im-field">密码<input v-model="password" type="password" autocomplete="current-password" required/></label><p>使用系统网络与代理。登录状态由系统加密保存，密码不保留。</p><button class="im-button im-primary" :disabled="busy">{{busy?'登录中…':'登录哔咔'}}</button></form>
  <template v-else><form class="source-search" @submit.prevent="search()"><Search :size="18"/><input v-model="query" placeholder="搜索漫画名称、作者…" aria-label="搜索哔咔"/><button class="im-button im-primary" :disabled="busy||!query.trim()">搜索</button><button type="button" class="im-button" :disabled="busy" @click="logout">退出登录</button></form>
    <template v-if="detail"><button class="im-icon" @click="detail=null"><ArrowLeft :size="16"/>返回搜索</button><h3>{{detail.work.title}}</h3><p class="source-meta">{{detail.work.author||'作者未标注'}} · {{detail.work.pages}} 页 · {{detail.work.finished?'完结':'连载中'}}</p><p class="source-description">{{detail.work.description}}</p><div class="source-selection"><label><input type="checkbox" :checked="selected.length===detail.chapters.length" @change="selected=($event.target as HTMLInputElement).checked?detail.chapters.map(c=>c.id):[]"/>全选章节</label><span>已选 {{selected.length}} 章</span></div><div class="source-chapters"><label v-for="chapter in detail.chapters" :key="chapter.id"><input v-model="selected" type="checkbox" :value="chapter.id"/>{{chapter.title}}</label></div><footer><select v-model="group" aria-label="下载漫画类型"><option value="">未分类</option><option v-for="g in store.groups.filter(g=>!g.hidden)" :key="g.id" :value="g.id">{{g.name}}</option></select><button class="im-button im-primary" :disabled="busy||!selected.length" @click="download"><Download :size="17"/>选择目录并下载</button></footer><p v-if="message">{{message}}</p></template>
    <template v-else><div class="source-results"><button v-for="work in results" :key="work.id" :disabled="busy" @click="open(work)"><strong>{{work.title}}</strong><span>{{work.author||'作者未标注'}} · {{work.chapters}} 章 · {{work.finished?'完结':'连载中'}}</span><small>{{work.tags.join(' · ')}}</small></button></div><div v-if="total>0" class="source-pagination"><button class="im-button" :disabled="page<=1||busy" @click="search(page-1)">上一页</button><span>{{page}} / {{total}}</span><button class="im-button" :disabled="page>=total||busy" @click="search(page+1)">下一页</button></div><p v-if="!busy&&!results.length" class="source-meta">输入名称搜索，查看作品后选择章节。</p></template>
  </template><p v-if="busy" class="source-meta">正在连接来源…</p><p v-if="error" class="im-error" role="alert">{{error}}</p><ImageDownloadList/>
</section></div></Teleport></template>
<style scoped>
.source-dialog{width:760px}.source-login{max-width:400px;margin:0 auto}.source-login p,.source-meta{color:var(--text-sub);line-height:1.7;font-size:12px}.source-search{display:flex;align-items:center;gap:9px;margin-bottom:22px}.source-search>input{flex:1}.source-results{display:grid;grid-template-columns:1fr 1fr;gap:12px}.source-results button{display:flex;flex-direction:column;align-items:flex-start;text-align:left;gap:9px;padding:15px;border:1px solid var(--divider);border-radius:7px;background:var(--bg-card);color:var(--text-main)}.source-results button:hover{border-color:var(--accent)}.source-results span{color:var(--text-sub);font-size:11px}.source-results small{color:var(--text-faint);font-size:10px}.source-results strong{font-weight:500;line-height:1.7}.source-pagination{display:flex;align-items:center;justify-content:center;gap:18px;margin-top:20px}.source-description{max-height:170px;overflow:auto;white-space:pre-wrap;line-height:1.7;color:var(--text-sub)}.source-selection{display:flex;justify-content:space-between;padding:12px 0}.source-chapters{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;max-height:210px;overflow:auto}.source-chapters label{display:flex;align-items:center;gap:8px;background:var(--bg-card);padding:10px;border-radius:5px}.source-selection label{display:flex;gap:8px}.source-chapters input{flex:none}
</style>
